tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
tap "thoughtbot/formulae"

brew "git"
brew "heroku/brew/heroku"
brew "jq"
brew "mongodb/brew/mongodb-community-shell"
brew "node"
brew "postgresql"
brew "thoughtbot/formulae/rcm"

cask "docker"
cask "google-chrome"
cask "iterm2"
cask "mongodb-compass"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
