tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "thoughtbot/formulae"
tap "fewlines-education/tap"

brew "git"
brew "gnupg"
brew "heroku/brew/heroku"
brew "jq"
brew "node"
brew "thoughtbot/formulae/rcm"
brew "sparta-cli"

cask "google-chrome"
cask "iterm2"
cask "mongodb-compass"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
