tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "thoughtbot/formulae"

brew "git"
brew "heroku"
brew "jq"
brew "node"
brew "postgresql"
brew "thoughtbot/formulae/rcm"
cask "atom"
cask "google-chrome"
cask "iterm2"
cask "slack"
