#!/bin/bash

function configureShell {
  expectedShell=/bin/zsh

  if [ "${SHELL}" != "${expectedShell}" ]; then
    chsh -s ${expectedShell}
  fi
}

function fixPermissions {
  compaudit | xargs chown -R "$(whoami)"
  compaudit | xargs chmod go-w
}

function installBrew {
  brewPath=${HOME}/.Brewfile

  if [ -e "${brewPath}" ] && ! brew bundle check --file="${brewPath}" > /dev/null; then
    brew bundle --file=${brewPath}
  fi
}

function installNodePackages {
  packages="eslint jest prettier"

  for package in ${packages}; do
    if ! npm list --global=true --depth=0 --parseable | grep ${package} &> /dev/null; then
      npm install --global ${package}
    fi
  done
}

function installVSCodePackage {
  code --install-extension dbaeumer.vscode-eslint
  code --install-extension esbenp.prettier-vscode
}

configureShell
installBrew
installNodePackages
installVSCodePackage
fixPermissions
